```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
# Julia {#Julia}

## Julia的一些体会

**关于类型**。Julia一些包会自己构造一些类型，我们很多时候需要访问这个类型的成员，但成员的名字往往并不事先知道。一般情况下，可以通过下面三种办法获知成员的名字：

- `dump(类型)`
- `fieldnames(类型)`
- 在帮助系统查看这个类型的帮助

### 关于函数的参数

参数本质上分两种，一种是按位置确认的参数。另一种是键值对参数。其按名字确认，位置随便。这两类参数在创造函数时要用分号隔开。

按位置确认的参数可以有默认值，记住这只是默认值，是不能按名字给它传参的。比如，
```julia
function addtwo(x, y = 1)
  x + y
end
addtwo(1,2) # 正常
addtwo(1, y = 3) # 报错,不能按名字传，除非是第二类键值对参数。
```

类似于R语言中`...`，它也可以传这种参数，但它需要在`...`前加一个名称，如
```julia
function addtwo(x, y = 1, z...)
  x + y
  println(z)
  println(z...)
end
```

函数体内可以直接调用`z`，但是此时的`z`是一个元组，很多时候我们需要把它展开，即以`z...`的形式调用。

## Julia的一些常用包
### 优化包

`Optim`包做单变量，多变量优化非常优秀，是最流行的一个优化包。比如我常用的单变量优化，里面就有黄金分割算法等。

### Julia数值求根

对于单方程求根，可以使用两个包如下。这两个包可以找到既定区间下所有的根。代码案例如下，
```julia
using IntervalArithmetic, IntervalRootFinding
f(x) = sin(x) - 0.1*x^2 + 1
a = roots(f, -10..10) # 第二个参数就是在`IntervalArithmetic`包中区间这个类型的表达方式
a[1].interval.lo # 返回第一个根的下界
```

这里有几个注意的地方:第一，`roots`返回的是`Root`对象，可以通过前面说的方法，查看它的成员字段，知道它有两个字段一个是`interval`，一个是`status`。我们需要前者，然后`interval`本身又是一个类型，于是按照前面的方法继续查看它的字段，一个是`lo`，一个`hi`。

### `DataFrames`包

## Julia的IDE体验

- Julia的一个IDE就是Atom中的Juno，它已经非常好用了。记录几个点：
  - 快捷键配置，是在一个文件中修改的，见https://blog.csdn.net/uniqsa/article/details/91315714。这个给一个我常用的运行和保存配置书写,注意缩进：
  
```
'.platform-darwin atom-text-editor[data-grammar="source julia"]':
  'ctrl-enter': 'julia-client:run-block'
  'shift-ctrl-enter': 'julia-client:run-all'

'body':
  'ctrl-s': 'core:save'
```

- VSCode这个IDE似乎更好用。记录几个快捷键备忘：
  - `ctrl+enter`执行本行命令但光标不往下走
  - `ctrl+shift`执行本行命令但光标往下走
  - `cmd+M`激活终端，这个是我自己设的。后来我发现它有个缺省的`ctrl+\``就是激活终端。
  - `cmd+1/2/3`在不同组的pane间切换。
  - `ctrl+1/2/3`激活第1/2/3个编辑器。
  - `esc`清除本行代码运行结果
  - `cmd+shift+p`调出命令面板，可以直接输命令执行
  - file菜单下可以打开文件夹，也可以打开工作空间。如果你只有一个项目，往往只需要打开文件夹，但如果你有多个项目同时运作，你可以保存为一个工作空间，然后以后以打开工作空间的形式来编辑代码。
  - 查bug，要用那个带小虫子的按钮运行。


## 其他tips

- 查看模块内都有些什么东西，用`names(MyModule)`，查看一个类里面都有什么东西，用`fieldnames(MyClass)`。
- 类似于R中`.rdata`的格式的数据保存，`JLD2`包的`jldsave("mydata.jld2")`使用。然后用`load("mydata.jld2")`来加载。
- 在Julia中变量按引用传递，举个例子如下。
```julia
a = [1,2,3]
b = a
a[1] = 10 # 此时b的值也会变成10，如果你想让两个变量不一样，你应该上一句使用b=copy(a)
```

- 安装包
```julia
import Pkg;
Pkg.add("DataFrames")
# Pkg.rm()是删除包
using DataFrames # 导入包
```

- `Pipe`包提供了强大的管道操作`|>`，与R语言中的`.`不同，它使用`_`作为占位符。
```julia
@pipe data |> addX(_[1],_[2]) |> println
```
- `1:5`返回的是一个迭代器，可以用`collect(1:5)`变成一个数组
- `using RCall, Statistics`可以同时导入多个包
- `mean(skipmissing([1, missing, 3]))`求均值忽略缺失值
- 查看模块中所有方法或变量`names(模块)`。通常是去github上看它的案例用法。
- 返回当前工作空间的变量，可以用`names(Main)`或者`varinfo()`
- 函数名字中带‘！’号，该函数不仅返回值，还会更改参数的值。
- 在Julia表达式中，如果要标志某个字符是变量，也就是它要被它的内涵所替代，前面要加美元符号。比如定义一个宏：
```julia
macro sayhello(name)
  :(println("Hello,",$name)) # 注意括号的使用
end
```
- 变量赋值
```julia
a,b,c = 1,'a',3 
```
- 一些函数可以作用于矩阵，如果在其后加个点意味着它作用于矩阵的元素，如
```julia
x1 = randn(6,4)
x2 = round.(x1)
```
- 创建矩阵的方式，和matlab有许多共通之处。拼接也是类似的。
```julia
A = [1 2 3 4;5 6 7 8 9];
A = randn(10,8) # 10行8列的正态分布矩阵
A = ones（6，5）
```
- `include`类似于R的`source`.



