```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# git操作流程
## 基本语法
- `cd E:/17_Huadong/` 到当前目录。
- `pwd` 查看当前目录是啥。

## 生成公钥
使用`ssh-keygen -t rsa -C "xxxxx@xxxxx.com"  `生成公钥，

- windows下，一般存在`C:\Users\Administrator\.ssh\id_rsa.pub`中。
- 在mac电脑，存在`~/.ssh/id_rsa.pub`文件中。

将公钥复制出来，添加到码云或github的公钥中即可。

## 本地库操作
1. 使用`cd`命令进入要同步的目录
2. 使用`git init`初始化
3. 使用`git add .`添加所有目录及该目录下的文件进入暂存区
4. 使用`git commit -m "your message"`递交更改
5. 使用`git reset --hard 3628164`进行版本回退，后面的数字为文件更改的唯一标识码。可以通过`git log`（查看提交历史）或`git reflog`（查看命令历史，回到未来版本）来找该码. 若是恢复到上一个版本，可用`git reset --hard HEAD^`命令。

- `git status`查看当前文件更改的情况，包括哪些文件修改了等等
- `git rm myfile.txt`从版本库中删除文件，然后·`git commit -m "message"`，若是删错了，可用`git checkout -- myfile.txt`恢复

## 关联远程库（码云）

1. 使用`git remote add origin git@gitee.com:jtdx/SomeApp.git`命令关联远程库（虽然我在码云的昵称为`common2016`，但此处是`jtdx`），注意反斜杠最后的字母是你的项目名称。不建议使用Https协议关联，这会使得后期推送都要输密码。建议用邮件的形式关联。
2. 使用`git push -u origin master`进行第一次全部推送。其中`master`表示在本地，你的库所在的分支是哪个。当前主分支默认不再是`master`而是`main`，因此，你应该把命令改成`git push -u origin main`。实际上，你可以通过`git branch`看当前目录下，你有几个分支：
```bash
* main
  dev
```
打*号的表示当前分支，dev是现存的另一个分支。

3. 今后则使用`git push origin master`进行推送即可
4. 从远程库更新本地库，用`git pull`
5. 其他：
    - 使用`git remote -v`查看关联的远程库地址
    - 使用`git remote rm origin`删掉名字为`origin`的远程库
    - 使用`git clone https://gitee.com/jtdx/HowBigHelpOfTheTeacher.git`复制所有文件到本地库。但https协议每次都要输密码。**但使用**`git clone git@gitee.com:jtdx/HowBigHelpOfTheTeacher.git`命令则不需要。当然之前，该台电脑的公钥要先添加进去码云。
    - 如果使用https协议传输，有时还会出现“SSL_ERROR_SYSCALL”的错误，解决该错误，就是更改为使用SSH传输,更改的语句为`git remote set-url origin git@github.com:xxx/xxx.git`
   
## 打开VI后的操作

当你没有设置默认文本编辑器时，会打开 vi。其基本操作是：

- 初始在正常模式，按 i （小写，即按 I 键）进入插入模式，写文本；
写完后按 Esc 回到正常模式
- 输入 :wq （依次按 <Shift-;> w q，会在末行
显示）保存更改并退出编辑器。

## 给递交进行标记

可如下标记当前的HEAD，参数`-a`是这个标记的名字，`-m`是这个标记的信息，然后递交至远程库。
```
git tag -a 'v0.1.0' -m 'add cp method' HEAD
git push origin tag v0.1.0
```

可如下查看所有标记,
```
git tag -l
```
查看标记更多的信息,
```
git show v0.1.0
```