```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = FALSE)
```
# macOS操作系统 {#OS}

## 一句话Tips

- `cmd+shift+.`显示隐藏文件。
- `shift+alt+-`输入破折号。
- 进入外置磁盘目录，要先进入根目录，然后输入`cd volumes`就可以看到外置磁盘的名字了。
- 苹果系统查命令的详细说明可以使用比如`man diskutil`就可以查看命令`diskutil`的详细语法，阅读完后，输入`q`以退出。
- 在macOS上安装dynare，国内会因为连不上github而无法安装。如何在国内顺利连上github，参考https://juejin.cn/post/7039913254897860616
- `chromedriver`可以放在`/usr/local/bin`目录下，在命令行使用`open /usr/local/bin`打开该目录。

## 安装和配置Latex

1. 安装texlive，在macOS下就是Mactex。进入Texlive官网，下载安装包，双击安装即可。
2. 安装TexStudio更加简单，下载后双击，把弹出的窗口中的程序复制到Applications里面即可。
3. 配置TexStudio，一是Build里面，引擎要换成xepdf，这是专门为中文进行渲染的。二是各种命令要换过来，具体可以参见旧的界面，或者https://blog.csdn.net/qq_14925953/article/details/126590499。

## Homebrew

- macOS上有一个优秀的包管理器Homebrew,进它的主页https://brew.sh/，一行代码让你装上该软件。注意，该软件同样要求你能够顺利连上github。很多情况下速度很慢，导致安装不上。可以如下步骤更换代码存储的源：
  - `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh >> brew_install`把安装过程的命令文件下载到你当前目录下。
  - 打开文件`brew_install`更改默认的源：
```
将默认的源
HOMEBREW_BREW_DEFAULT_GIT_REMOTE = "https://github.com/Homebrew/brew"    
HOMEBREW_CORE_DEFAULT_GIT_REMOTE = “https://github.com/Homebrew/homebrew-core“
修改为  
HOMEBREW_BREW_DEFAULT_GIT_REMOTE = "https://mirrors.ustc.edu.cn/brew.git"
HOMEBREW_CORE_DEFAULT_GIT_REMOTE = "https://mirrors.ustc.edu.cn/homebrew-core.git
```
- 终端运行命令`/bin/bash brew_install`即可。最后依据终端的提示，添加brew的路径。
如果出现`fatal: Could not resolve HEAD to a revision`报错。按如下步骤解决：https://www.jianshu.com/p/54beebb59570。

- 当有了brew命令之后，安装jdk是非常简单的一件事。可以在homebrew搜索jdk的安装命令，它是`brew install --cask oracle-jdk`。有了jdk，我们就能愉快地使用R语言的xlsx包了。


## 挂载外置磁盘

1. 首先利用`diskutil list`查看你的外置磁盘的设备名称，在IDENTIFIER列中，一般是`/dev/disk4s2`之类的。
2. 然后利用`diskutil info disk4s2`查询磁盘的UUID
3. 然后设置开机挂载。命令行`sudo vim /etc/fstab`打开文本文件，输入如下:
```
UUID=06A19C31-BED5-36E9-BEC9-616E398C77FD /Users/yangnay/elements exfat rw,auto
```
注意，`exfat`是你的硬盘的文件格式，`elements`需要提前建好文件夹。

## 定点运行R程序

在Mac电脑上，可以使用“Automator”来定点运行一个程序。以下是详细步骤：

1. **打开Automator**：
   - 在“应用程序”文件夹中找到并打开“Automator”。

2. **创建新文档**：
   - 选择“新建文档”，然后选择“日历提醒”作为文档类型。

3. **添加运行程序的操作**：
   - 在左侧的“库”中，找到“实用工具”。
   - 拖动“运行Shell脚本”或“运行AppleScript”到右侧的工作区。
   - 在脚本中输入启动R程序的命令。例如，如果要启动“终端”，可以输入：
     ```bash
     Rscript ~/检测.R
     ```

4. **保存Automator工作流**：
   - 点击“文件” > “保存”，为工作流命名，并选择“日历”作为保存位置。

5. **设置日历事件**：
   - 打开“日历”应用，创建一个快速日程。里面可以修改程序运行的时间、周期等。
   - 在事件的提醒中选择“打开文件”，然后选择你刚刚创建的Automator工作流。

