```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = FALSE)
```
# 其他小众软件 {#Other}

## PDF文件压缩

github上有个项目，windows下压缩PDF

项目地址：https://github.com/pgodwin/PdfShrinker

- 文件名不要有中文

## Eviews编程
- 单引号`'`意味着评论。
- 一行写不完，用下划线表示下一行接着来`_`，就像matlab里面的`...`。
- 

## GAUSS

- 可以使用学生证申请它的light版，(网址)[https://www.aptech.com/industry-solutions/gauss-in-education/students/]
- F4类似于R里面的`ctrl+enter`，如果选中则运行选中行，没选中则运行当前行。运行整个代码使用Ctrl+R。
- GAUSS在函数中，如果没有使用类似`local x y`方式定义的变量，都是全局变量，会在函数中修改函数外的值。
- `#include myfile.src`将`myfile.src`文件中的内容插入到当前脚本中，类似于R语言中的`source()`。但是该命令不能在控制台执行，而只能嵌入在脚本中。要在控制台中达到相同的效果应该使用`run myfile.src`。通常可以把函数都放在`.src`文件中。
- GAUSS也有自己的库，它调用库的命令与R类似，如`library pgraph; `
- `a|b`垂直连接矩阵a和b, `a~b`水平连接矩阵a和b。
- 右下角有个按钮可以悬浮整个窗口，还不错。

### 系统函数

- `cdir(0)`返回当前工作目录
- `chdir E:\17_HuaDong\learn\HM2009\PythonCode\ch9_code_2nd_gauss;`修改当前工作目录

## Zotero

主要看看它的参考文献格式编辑，这个编辑是CSL语言，和html语言在格式上是互通的。这个语言不仅使用Zotero，也是适用EndNote的。先介绍三个工具，

- 这是一个手把手的教程，入门非常合适 https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step 。
- 这是它的可视化CSL编辑器，可以在里面所见即所得的编辑 https://editor.citationstyles.org/visualEditor/ 。
- 这是关于它的很多细节设置，包括choose这类标签的使用等 https://docs.citationstyles.org/en/stable/specification.html。
- 这上面有很多中文格式，直接下载稍作修改即可使用，包括《经济研究》、《管理世界》等。 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl 。我在上面下载安装了Business Management Journal这个样式，还不错，可以做一个通用版本。

基本流程就是：
 
- 先找一个和你想要的格式非常类似的已存格式，可在前面第二点的网址中找。
- 找到后，要先改它的样式的Title和ID，否则当你保存了这个样式，去安装的时候，只会覆盖原来的样式，不会产生新的样式。

## Word中插入公式

### 自带的公式输入

1. latex形式输入公式。`alt + =`就会弹出公式输入框，可以选择以latex的形式输入
2. 插入公式编号。公式#(1)回车，就有公式编号。
3. 公式换行。shift + enter就可以输入多行公式；可以在=处右键“在此字符处对齐”。
4. 公式换行和对齐。见 https://blog.csdn.net/qq_43874317/article/details/130170680。

### 公式编号的其他方法

- 通过“样式”的形式来设置公式居中，编号居右。比如设置制表位20时居中，40时居右。这样两个tab键就可以使公式居中，编号居右。
- 公式编号最好采取书签形式。首先选中比如插入的题注`（1）`,然后“插入-书签”，给这个书签命名，后面引用时直接引用这个书签。这样就不会出现题注引用连着改行的文字一起引用。

（这个是以前的办法：公式编号最好用题注的形式进行，但插入题注前用`ctrl + alt + enter`键来插入一个样式分隔符，这样在后面公式引用时就不会连着该行的文字一起引用。）

### 利用TexsWord编辑器

该软件最大的好处是公式编号。软件百度下，是免费下载的，2016年停止更新了，但使用效果没有变化。

下载以后把它的.dotm文件复制到启动文件夹下，重新打开Word就能看到加载项选项，然后可以使用。
启动文件夹位置为（或者你也可以找到定位到模板文件所在位置，然后往上一层就能看到启动文件夹）：

- `/Users/yangnay/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Startup.localized/Word`


## NoteExpress样式设置

- 参考文献中文在前，英文在后，首先把文献的字段“语言”凡是英文的改为"English"，然后排序的时候先按语言排即可。
- 对于空格的处理，以`*`号连接，如
```
作者.标题[J].期刊,年份,卷|(期)|:*页码|.
```
- 一般情况上述格式中的标点符合与前面一个字段关联，如`年份`后面的逗号与`年份`同时出现，同时消失。如果想要标点符号和后面的字段关联，则要使用`|`符号。
- 虚拟机安装NoteExpress弹出一个包含乱码的报错窗口，解决办法见 https://www.zhihu.com/question/514427851/answer/2421268390 。
- "无效的类字符串报错"解决办法见 https://jingyan.baidu.com/article/4b52d702755cd0fc5c774bc8.html 。

## FileZilla
这个文件传输文件不是一般地快。

官网下载地址：https://www.filezilla.cn/

几个问题的处理：

- 很多时候直接就是连不上。做两个动作：
  - 改客户端的文件传输为FTP，下面那个框框的选项是明文传输；
  - 服务端的电脑，更改防火墙设置，把21端口开放。[具体见这里](https://blog.csdn.net/InnovationAD/article/details/84944238?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control&dist_request_id=1db1882b-159d-4705-865f-78d855fe1f50&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control)

- 如果报错：425 Can't open data connection。还是要更改服务端电脑的防火墙设置，[具体见这里](https://blog.csdn.net/weixin_44284051/article/details/106277683)